### ISSUE TITLE
download updated ES

### ISSUE THREAD

**Issue by jrassa** [Francommit/win10_emulation_station#1]
Saw this on reddit.  Regarding inability to script the download from github, you can try getting them from appveyor instead using the link below.

https://ci.appveyor.com/api/projects/jrassa/emulationstation/artifacts/EmulationStation-Win32.zip?branch=master

**Comment by Francommit** [comment]
Hey jrassa,

Looks like I need some sort of temporary token to download it:

![image](https://user-images.githubusercontent.com/11533365/30374124-2b210f10-98c7-11e7-990a-4cdbcd95a8c0.png)

**Comment by Francommit** [comment]
@jrassa Do you by any chance think you'll be able to provide a different mirror?
I'm ok temporarily putting it into Google-Drive then updating it when need be but I feel like that's a terrible solution.

**Comment by jrassa** [comment]
@Francommit I did some testing and I was able to download the release from github using the following.

```ps1
Invoke-WebRequest -Uri https://github.com/jrassa/EmulationStation/releases/download/continuous/EmulationStation-Win32.zip -OutFile EmulationStation-Win32.zip
```

**Comment by Francommit** [comment]
Hahaha thanks jrassa. I literally made this 10 minutes ago :)

![image](https://user-images.githubusercontent.com/11533365/30508327-e27858e6-9ad7-11e7-99cf-c9fa61e90441.png)

**Comment by jrassa** [comment]
@Francommit You shouldn't have to pull the releases list.  The continuous release always has the latest build.

**Comment by Francommit** [comment]
@jrassa Whilst your repository does. I plan to re-use this downloader to acquire some custom themes that don't use tags in the same correct manner that you do. Unless this is some feature of Github I've overlooked, because it looks like other repositories don't quite use their tags in the same manner.
