### ISSUE TITLE
Github has changed their site to something other than TLS 1.0

### ISSUE THREAD

**Issue by DasKatzchen** [Francommit/win10_emulation_station#10]
If you add `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"` somewhere appropriate near the top it starts working again.

**Comment by Francommit** [comment]
Thanks! Are you happy to make a PR and add it in or I can do it now myself :) ?

**Comment by DasKatzchen** [comment]
I made a pull request just because I don't get to do it often.

**Comment by Francommit** [comment]
Thanks for your help DieKatzchen! Glad people are actually using the script!
