### ISSUE TITLE
jrassa Build of emulationstation's forward slashes not working with fbalpha_libretro.dll

### ISSUE THREAD

**Issue by rubenjavier** [Francommit/win10_emulation_station#12]
Hello everyone, Im not really sure where to report this issue, maybe with some luck @jrassa will see it here.

This is all tested in windows 10 64bits and retroarch 1.7.1
as the title says, Portable Game Station with the emulationstation from march 12 https://github.com/jrassa/EmulationStation/releases is not working because even if the <path> label have backward slashes, the lauch command writhes the path with forward slashes.
fbalpha_libretro.dll its the only core that is failing in my testing so far because of the slashes

this works:
C:\Portable-Game-Station\.emulationstation\systems\retroarch\retroarch.exe -L C:\Portable-Game-Station.emulationstation\systems\retroarch\cores\fbalpha_libretro.dll M:\fba\mslug.zip

this does not work:
C:\Portable-Game-Station\.emulationstation\systems\retroarch\retroarch.exe -L C:\Portable-Game-Station.emulationstation\systems\retroarch\cores\fbalpha_libretro.dll M:/fba/mslug.zip

I've tested nes, snes, atari, gb, gbc, mastersystem, megadrive, nds, n64 and those cores are working correctly with the forward slashes that emulationstation/Portable-Game-Station are forcing

Update:
For what I could find, its "%ROM_RAW%" not working correctly, in a post from 2015, ROM_RAW behaviour was changed to be able to write the slashes correctly according to the O.S. because VLC asked for this, but seems to be broken in this last version of emulationstation
https://emulationstation.org/news/?p=17

maybe something was changed in the emulationstation code because now all of the paths that show on the log have forward slashes an none have the O.S. backward slashes..
Also I have found that fbalpha_lobretro care only about the last slahs, the one just begore the rom name

this works:
C:\Portable-Game-Station>.emulationstation\systems\retroarch\retroarch.exe -L C:\Portable-Game-Station\.emulationstation\systems\retroarch\cores\fbalpha_libretro.dll M:/fba\mslug.zip

this does not works:
C:\Portable-Game-Station>.emulationstation\systems\retroarch\retroarch.exe -L C:\Portable-Game-Station\.emulationstation\systems\retroarch\cores\fbalpha_libretro.dll M:/fba/mslug.zip

Thanks in advance
best regards

**Comment by Francommit** [comment]
Hey rubenjavier,

Probably best to raise it over at the Portable Game Station GitHub.

Thanks.
