### ISSUE TITLE
Add more emulators and out-the-box settings

### ISSUE THREAD

**Issue by ngosang** [Francommit/win10_emulation_station#14]
First of all, thank you for he script. It save me precious time.
After the changes I made in #13 , the installation in fine but there are things that don't work out-the-box. 

PSX emulator:
1) Bios is missing, It's ok
2) First time I have to set up CPU overclock and other things in the ePSXe gui. => We could edit ePSXe config in the script
3) I have to set up the controller in the ePSXe gui. => I don't know if it's possible to use the retroarch config (or emulestation config)

Retroarch controller:
1) After configuring controller in Emulestation, I was expecting the controller to be working in all games. I had to open retroarch.exe and configure the controller again => I don't know if it's possible to reuse Emulestation configuration. I think RetroPie does that.

Other emulators:
1) I installed libretro MAME and PCSX2 (Play2). => I can update the installation script if anyone is interested. The thing is, if we add more emulators some of them should be optional.

Is anyone interested in improving the script?

**Comment by Francommit** [comment]
Hey ngosang,

Regarding the bios, we simply can't automate that, it's an illegal file.

In regards to ePSXe setup, I've personally never set it up. But if you have a ".config" or something else that you've pre-configured we can do something similar like how I inject the config file into emulation station to get menu elements to appear "switched on" without configuring them.

Regarding the new emulator, add it in! The more that's automated for a wider audience the easier things will be moving for others to pick things up and go!

**Comment by ngosang** [comment]
Done in #15
