### ISSUE TITLE
just says checking for config file

### ISSUE THREAD

**Issue by scrummie02** [Francommit/win10_emulation_station#19]
During the install i get the following errors:
`puae_libretro.dll.zip does not exist...Downloading.
Start-BitsTransfer : The operation being requested was not performed because the user has not logged on to the
network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
At E:\win10_emulation_station-master\prepare.ps1:30 char:9
+         Start-BitsTransfer -Source $url -Destination $output
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.BackgroundIntelligentTransfer.Mana
   gement.NewBitsTransferCommand`

After that it just says checking for config file over and over.  This is on Windows 10 pro

**Comment by PRElias** [comment]
It looks like you or the server had just a connection problem or something like that. I tried the URL on the browser and downloaded the file sucessfully. I tried the script many times as well. 

Have you tried to update your Powershell?

I recommend you to simply try again too, but I'll be investigating further and thanks for your comment

**Comment by scrummie02** [comment]
You have to log in as admin in order to do it.  I figured it out.  If you're just doing run as it won't work

**Comment by scrummie02** [comment]
also the scraper version is updated 4.6 and you have 4.5.  It's a quick change in the script

**Comment by Francommit** [comment]
Hey @scrummie02 ,

Are you reffering to running the powershell script as an administrator? That's listed in step 3.

RE: the scraper - it'll always grab the latest version of sselph/scraper from the dev's github release page.

**Comment by scrummie02** [comment]
The script looked for 4.5 even 4.6 is out.

**Comment by ZXDunny** [comment]
Can confirm - just tried and it's tried to download 4.5 and failed.

**Comment by PRElias** [comment]
You're right. It downloads the last version but asks the specific one on unzipping. I'll try to look for a solution on this.

Thanks

**Comment by scrummie02** [comment]
I had to change the script and it works

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by PRElias** [comment]
Included a fix for this on my last PR

**Comment by Francommit** [comment]
This is now fixed in @PRElias's latest commit.
