### ISSUE TITLE
Integrate theme recalbox-backport

### ISSUE THREAD

**Issue by fonic** [Francommit/win10_emulation_station#25]
If you like, you can integrate my theme _recalbox-backport_, which I recently created. It's a backport of the current theme _recalbox-next_ to the old theming engine, offering more systems and support for auto-collections _last played_ and _all games_.

Link: https://github.com/fonic/recalbox-backport

**Comment by Francommit** [comment]
Hey mate,

Nice work, I've done just that and it looks fantastic! 

Thanks for your work!

**Comment by Francommit** [comment]
Hey mate - any chance you can create a 'release' ?
Having trouble downloading master.zips off github

**Comment by fonic** [comment]
Sure, I'll create a release later today.

**Comment by fonic** [comment]
Done -> https://github.com/fonic/recalbox-backport/releases

**Comment by fonic** [comment]
I'll also update the theme to integrate the latest changes from the original, not today, but in the next couple of weeks. I'll let you know here when I'm done.

**Comment by Francommit** [comment]
Hey fonic,

I managed to get it to work with some dodgy-naming in the main prepare script.
Could you possibly not but the name of the release in the name of the zip file in your next update?

For now though, works like a dream - thanks!

**Comment by fonic** [comment]
I'll add a `-francommit.zip` to the releases that will just have a `recalbox-backport` folder. I'm currently updating the theme, I'll let you know when it's done.

**Comment by fonic** [comment]
I'm done with the update. Wow, this was A LOT of work, but the result is great. I was able to fix almost all display glitches I could find and also added some custom graphics of my own. Looks better than ever before.

The release archives no longer contain subfolders with version info, so you can revert your 'dodgy-naming' back to normal ;)

**Comment by Francommit** [comment]
Everything is appearing as;

"Panasonic REAL 3DO" in v2

**Comment by fonic** [comment]
> Everything is appearing as;
> "Panasonic REAL 3DO" in v2

Just tested this with a clean install as I couldn't believe it ;) This happens when you put the theme contents directly into `.emulationstation\themes`. This won't work, it needs its own subfolder, e.g. `.emulationstation\themes\recalbox-backport`.

**Comment by Francommit** [comment]
Less beer while testing I reckon!

**Comment by fonic** [comment]
> Less beer while testing I reckon!

Oh no, beer is never wrong ;) But it's actually quite an interesting glitch you found there, all 3DOs looks hilarious ;)
