### ISSUE TITLE
BITS transfer fails in prepare.ps1 if via VPN

### ISSUE THREAD

**Issue by thadeshammer** [Francommit/win10_emulation_station#29]
To be clear, I don't see this as an issue with your software, but you may want to consider making a note of it in the README? While my VPN was active, script execution would block here, repeatedly checking for a config file.

<img width="600" alt="emultationStationError" src="https://user-images.githubusercontent.com/17990441/77123592-eca0b000-6a16-11ea-997e-8df637d8f46d.PNG">

The actual error was above (it failed to get RetroArch, saying no adapter was available, after successfully pulling down choco).

<img width="606" alt="emulationStationError2" src="https://user-images.githubusercontent.com/17990441/77123660-25d92000-6a17-11ea-8f6a-fd1039e09b4a.PNG">

Overall, this script was super helpful; thanks for making it.

**Comment by Francommit** [comment]
Hey mate,

What type of VPN were you using?
I've tested it with my own VPN and it's worked a treat.

Were you on a corporate VPN by any chance where they were possibly blocking certain domains?

**Comment by Francommit** [comment]
Hey mate,

You'll be happy to know I've moved away from BITS.
So there should be no more VPN problems!

Cheers.
