### ISSUE TITLE
Cores-v1.0.0.2-64-bit.zip

### ISSUE THREAD

**Issue by evanerwee** [Francommit/win10_emulation_station#3]
The file is no longer available. Can this simple be remove from the list of files or will this missing file have an impact ?

**Comment by Francommit** [comment]
It's probably been updated! I'll go and grab the new version now!

**Comment by Francommit** [comment]
Ok. Turns out I've been using ancient cores! I'll update this to grab the SPECIFIC new files we need when I get a chance!

You can temporarily grab the cores you need from here: https://buildbot.libretro.com/nightly/windows/x86_64/latest/

**Comment by evanerwee** [comment]
You are more than kind. I appreciate you looking into the 'issue' and thank you for this excellent peace of work. I still try to get some time to code but we can all agree the world went crazy. As a DevOps architecture I can see that somehow there is so much work that everyone is always working.

**Comment by Francommit** [comment]
Hey evanerwee thanks for raising this.

Turns out I wasn't actually using this archive at all so I've just removed it from the script!
Everything should work correctly.

Let me know if anything else comes up. 

Thanks mate!
