### ISSUE TITLE
Is it possible to select a different folder or drive for the ROMS?

### ISSUE THREAD

**Issue by diegopau** [Francommit/win10_emulation_station#30]
In the README it says "Access your ROMS here %UserProfile%\.emulationstation\roms"

For a large number of ROMS I would prefer a different hard drive for storing them, is this possible and easy to change?

**Comment by PRElias** [comment]
If you inform other folder than the "OneDrive" folder, the script will use that one, however all ROMs are always set to the same directory.

If you intend to use more paths you'll need to change it manually on the script file

**Comment by diegopau** [comment]
@PRElias thank you! just one more thing, I already run the script yesterday (worked perfectly) so now if I change the folder "OneDrive" folder and I run the script again will be alright or should I first look into how to uninstall anything and start over?

**Comment by Francommit** [comment]
You could make a symlink to your HD so you can leave everything in tact?

**Comment by diegopau** [comment]
That worked, thanks!!
