### ISSUE TITLE
Weird sentence in README

### ISSUE THREAD

**Issue by fonic** [Francommit/win10_emulation_station#34]
Just read the README and tripped over this:

Optional Features and Tips
------
- If you prefer to run your scripts using context menu (right mouse button) but lacks the abilitiy to run they on an admin session, you can just double-click "powershell_run-as-admin.reg" file and accept the registry modification. It creates a new entry on the menu to do that easily.

This seems weird. My best guess is you meant something like this:

Optional Features and Tips
------
- If you prefer to run your scripts via context menu (right mouse button) but lack the abilitiy to run them in an admin session, you can just double-click the "powershell_run-as-admin.reg" file and accept the registry modification. It will add a new entry to the menu to do that easily.

**Comment by Francommit** [comment]
Updated it - thanks!
