### ISSUE TITLE
Dolphin Emulator not starting

### ISSUE THREAD

**Issue by Piyochon** [Francommit/win10_emulation_station#35]
The Dolphin Emulator from the retroarch will not open from both emulationstation or retroarch. When the dolphin was started from retroarch, the whole thing freezes and won't respond.

**Comment by Francommit** [comment]
Hey mate,

I've swapped out DolphinRetroArch for just Dolphin itself.
I've tested it and it appears to be working for me.

Could you uninstall and try again from a clean slate please?

**Comment by Piyochon** [comment]
Thanks for the quick response. I've got it to work with Dolphin itself and now it works! Thanks!
