### ISSUE TITLE
PSX2 emulator plugin directory address is incorrect

### ISSUE THREAD

**Issue by Piyochon** [Francommit/win10_emulation_station#36]
Plugins are not located within the directory? but they are there. The second I added where they are located, it was able to pull the information. However, the game still won't boot up. Some other directory still didn't work...

**Comment by Francommit** [comment]
Hey mate,

it's because the executable is in some $temp dir

**Comment by Francommit** [comment]
Corrected in the latest commit:

.emulationstation\systems\pcsx2\$TEMP\PCSX2 1.6.0\pcsx2.exe %ROM% --fullscreen --nogui</command>

**Comment by Piyochon** [comment]
Thanks! I ended up moving the the pcsx2.exe, the plugins, and the bios out of the temp file and change the config file to the correct path! It works for me now.
