### ISSUE TITLE
Script errors and goes into endless loop - Cause found

### ISSUE THREAD

**Issue by stephenegriffin** [Francommit/win10_emulation_station#4]
Revisiting #2.

Looking at the script, we're waiting for emulationstation.exe to create a config file. This reminds me that before I came here, I had tried to install ES myself. Maybe I should let the script install it instead? So I uninstall ES from Apps and Features and try the script again. Still fails. Apparently, choco thinks it's still installed, so it doesn't reinstall.
So I ran the choco install with --force. And now the script gets past the config bit!
Conclusion: Step 3 needs work. ES can be missing, or ES can be present, but for whatever reason does not generate a config file. Both conditions should be handled.

**Comment by Francommit** [comment]
Hmm I see what you mean. Might write some of my own 'Emulation Station' config logic instead of letting chocolatey handle it as it can get into a potentially borked state. Thanks!

**Comment by Francommit** [comment]
Hey Stephengriffin is this still an issue? I think using the force command fixes this.

**Comment by stephenegriffin** [comment]
Probably fixed. I’ll file a new bug if I dig up another repro.

**Comment by manugarri** [comment]
Still an issue @Francommit ,  script gets stuck at 
``` 
Checking for config file...
Test-Path : Access is denied
At C:\Users\manuel\...\win10_emulation_station-master\prepare.ps1:88 char:10

+ while (!(Test-Path $configPath)) {  
+          ~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\Users\manuel...\es_systems.cfg:String) [Test-Path],
UnauthorizedAccessException
+ FullyQualifiedErrorId

ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.TestPathCommand                                                                                                                                                                                                                                                                                     
```

**Comment by manugarri** [comment]
nevermind, uninstalling ES and restarting the system did the trick for me
