### ISSUE TITLE
starting path in powershell could make a diff between success and failure. 

### ISSUE THREAD

**Issue by msmick** [Francommit/win10_emulation_station#42]
FYI, I ran this from powershell as administrator (I'm no pro at this mind you).  When I right clicked to run powershell as admin,  powershell started default in the directory as system 32.  First time I ran the script from that directory, not really paying attention and while it did process some, it ended up hanging up later on and I had to Ctrl-C to kill it.  

I reran the script again as admin, but this time my starting directory in powershell was just my home directory, you know C:/Users/YourName/  and the script worked that second time.  So where you start probably matters. I don't know if this is worth adding to the instructions or anything but just an FYI.

**Comment by Francommit** [comment]
Hey, a very valid point, I might just make a dir C:\temp\es\ if it doesn't exist already, then run from there?

**Comment by msmick** [comment]
you're probably on the money with that temp directory idea. If the script can create that folder and put you in the right directory so no relative pathing can hang it up...  and do its thing, why not. I mean as long as you're of course not intending anything temp to be the perm location of installed programs, because people are gonna delete that folder on occasion manually or via some cleaner softwares too.

**Comment by Francommit** [comment]
Beauty, I'll set it up tonight then!
Thanks for the suggestion!

**Comment by Francommit** [comment]
Hey @msmick , sorry it took so long, life can get away from you sometimes.
I've updated the 'one liner' to the following;

```
if (-Not (Test-Path C:\temp)) { mkdir C:\temp }; mkdir C:\temp\es-setup\; Set-Location C:\temp\es-setup\;Set-ExecutionPolicy Bypass -Scope Process -Force;[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;Invoke-WebRequest "https://github.com/Francommit/win10_emulation_station/archive/1.1.1.zip" -OutFile "emulationStation.zip";Expand-Archive .\emulationStation.zip;cd .\emulationStation; cd .\win*;.\prepare.ps1
```

Which has just really been appending this:
```
if (-Not (Test-Path C:\temp)) { mkdir C:\temp }; mkdir C:\temp\es-setup\; Set-Location C:\temp\es-setup\;
```

I feel like I don't want to do any directory changing from within the script itself in-case people want to download the script separately and run it themselves from their own directory!

Thanks again for the suggestion!

**Comment by Francommit** [comment]
This is now done!
