### ISSUE TITLE
How to properly uninstall it?

### ISSUE THREAD

**Issue by moviapp** [Francommit/win10_emulation_station#49]
Hi! I want to reinstall because of some errors in my first attempt. 

Since the installation is based on script, how is the proper way of achieving a clean uninstall?

**Comment by Francommit** [comment]
What went wrong, you CAN rerun it, it'll spit our some errors about
duplicate files but they're typically fine.

**Comment by keenerb** [comment]
Mine aborted because chocalaty was already installed, and when I deleted chocolatey it complains that scoop is already installed.

Neither error will permit it to progress.

**Comment by Francommit** [comment]
This should perform a 'uninstall and removal' of everything it sets up.
```
choco uninstall emulationstation -f
scoop uninstall citra-nightly
scoop uninstall ppsspp
scoop uninstall yuzu
scoop uninstall rpcs3
rm C:\temp\es-setup
rm "%UserProfile%\.emulationstation\"
```
