### ISSUE TITLE
clean install on Win10 - msvcr100.dll was not found

### ISSUE THREAD

**Issue by Muertismo** [Francommit/win10_emulation_station#50]
Just ran the script to install on a fresh installation of Windows 10 Pro.  Launching the Windows Emulation station shortcut on the desktop, I get ;   emulatoinstation.exe - System Error   The code execution cannot proceed because MSVCR200.dll was not found. Reinstalling the program may fix this problem."  Basic googling for correcting this error suggests reinstalling visual C++2010 SP1 updates - which I did to no effect.

**Comment by Francommit** [comment]
Hey mate, 

Been busy with life - did you ever resolve the issue?

Any chance you were using Windows 10 Pro N or something odd like that?

**Comment by rafalmaciejewski** [comment]
I had the same issue on Windows 11. I installed and reinstalled many Visual C++ redistributable packages. Only after installing both x64 and x86 versions of VC++2010 SP1 i got it working.

**Comment by Francommit** [comment]
I've added this troubleshooting step - thanks @rafalmaciejewski 

https://github.com/Francommit/win10_emulation_station/commit/abeccc6f35d747293b9c65cb04d3f4b33e243d19#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

That chocolatey package should install both of the required packages.
I'm not adding it to the script as I recall I had problems with them in the past in certain circumstances.
