### ISSUE TITLE
scraper does not work

### ISSUE THREAD

**Issue by NeoFax75** [Francommit/win10_emulation_station#51]
Here is the error I get:

ss: cannot parse response: "invalid character 'F' looking for beginning of value"

also, sselph's scraper does not compile for me using go.

**Comment by Francommit** [comment]
Hey mate,

Think there might be something wrong with your setup.

I just ran it and it appears to be fine;
![image](https://user-images.githubusercontent.com/11533365/148643266-3c551fd8-40b2-416e-ab64-41e3ac8aa0db.png)

Are you possibly using a version that you compiled yourself?
I suggest raising an issue here - https://github.com/sselph/scraper

**Comment by Francommit** [comment]
Closing this as I haven't had a reply in a while - happy to re-open if you need some help.
