### ISSUE TITLE
Dolphin config path

### ISSUE THREAD

**Issue by kthornbloom** [Francommit/win10_emulation_station#55]
Hey, most of all, I just wanted to say that you're an amazing human for making this. What a time saver!

Also, I thought I'd mention that I noticed WII/Gamecube games crashed immediately, so after looking into it, I found that the config file was pointing to the wrong folder name for the Dolphin core. The actual folder installed by the script was named Dolphin-Beta or something like that.

**Comment by Francommit** [comment]
Hey - thanks, appreciate it.

This is a good catch - there was recently a problem with the **regular** dolphin choco package so I just bumped it to the pre-release to get the main build working.

I've updated the folder structures after installing it locally and checking the path.

Cheers!

https://github.com/Francommit/win10_emulation_station/commit/997ce487bf437295e326c6a9cdd5856307bde4b4
