### ISSUE TITLE
start + select button mapping don't seem to quit emulator

### ISSUE THREAD

**Issue by tr3v0rb** [Francommit/win10_emulation_station#57]
hi team,

setting the select button as the hot key, pressing start and select together doesn't seem to quit any emulator via EmulationStation.

I remapped the start and select keys directly in retroarch to test and it works okay

I hope it's not anything simple I am missing!

Cheers

Trev

**Comment by Francommit** [comment]
Hey mate - quitting in an emulator has to be done via the emulation tool itself - once emulationstation has launched it only looks to see if the exe that it launched it still running AFAIK
