### ISSUE TITLE
minimal installation

### ISSUE THREAD

**Issue by eadmaster** [Francommit/win10_emulation_station#59]
the  one liner to install everything is taking a lot of time to finish on my machine.

is it possible to perform a minimal installation, and download the emulators manually later?

UPDATE: as alternative i've found this fork: https://www.es-de.org/

**Comment by Francommit** [comment]
Define minimal? The whole script in it's current state is pretty minimal
IMO.

**Comment by eadmaster** [comment]
Minimal = only the launcher without any emulator preinstallled.

**Comment by Francommit** [comment]
I recommend going to jrassa' repo and downloading the compiled binary
directly. I forked his repo at a point in time as his daily cicd was
breaking but he's fixed it since then.
