### ISSUE TITLE
EmulationStation Crash

### ISSUE THREAD

**Issue by manurafal** [Francommit/win10_emulation_station#61]
System: Windows 10 Pro with Retrobat 6.4

CPU: Intel Core i5 2400

Hard Disc: WD 4TB NTFS

Memory: 16GB

Grafic Card: Nvidia Gforce GT 1030 LP 2GB DDR5

Problem:

When I move through the menu, Retrobat suddenly closes randomly, it happens randomly with any system. The error that appears in the es_log.txt file is the following:

2024-08-29 16:54:09 ERROR Error - Failed to load image from memory!
2024-08-29 16:54:09 ERROR Could not initialize texture from memory, invalid data! (file path: D:/RetroBat/emulationstation/.emulationstation/themes/es-Hypermax_Plus_v9/frogger/char.png, data ptr: 71,004,192, reported size: 1,262,596)

I have checked the PNG file and it is correct. The error is random, sometimes it is a PNG, other times it is an MP4, or an OGG, or an MP3, and I have always checked the files and they are correct.

[es_log.txt](https://github.com/user-attachments/files/17899408/es_log.txt)

**Comment by manurafal** [comment]
![389292294-39ae36f6-b2b6-4e4b-949d-22898a98695f](https://github.com/user-attachments/assets/0f32ce4d-4b5c-4f66-90d2-80bb18b55abd)
![389292296-10a1e902-0aaa-4a3f-a068-b18878f69854](https://github.com/user-attachments/assets/0b68e46b-7d2b-405e-8cfa-f1dc7b1ddeec)
![389292297-b54453e6-fe75-42f3-98db-1c09bb8dadac](https://github.com/user-attachments/assets/7205c463-1c46-40e0-b37f-cc6f9c27e7e7)
![389292298-7c69aaea-9cd4-4eb9-84e5-11644639ae99](https://github.com/user-attachments/assets/20da5e35-c82d-4071-a389-66ebcbded31a)
![389292301-75f9d8dc-fa3a-44e4-96e2-0bc6a0bef3c2](https://github.com/user-attachments/assets/b2ac5cf3-159f-4a58-b65b-32a58a4a1e02)

**Comment by manurafal** [comment]
![386958801-aaf5f9ad-d5b0-410a-bd5b-45ffb3fb6db5](https://github.com/user-attachments/assets/ed48e2e9-6ae5-4c3e-af3c-8add0ff36e3c)

**Comment by Francommit** [comment]
Hey mate. 

This script has nothing to do with Retrobat.
